# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            RDFBones
tagline:          'Semantic Science'
description:      'Making Research Explicit'
url:              https://rdfbones.github.io

author:
  name:           'Stefan Schlager'
  url:            http://rdfbones.github.io

paginate:         5
paginate_path: /page:num/

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/rdfbones
  
excerpt_separator:	<!--more-->

# Gems
gems:
 - jekyll-coffeescript
 - jekyll-paginate

kramdown:
   input: GFM
   hard_wrap: false
   syntax_highlighter: rouge
